-- SiteForge database (Postgres: Supabase in production, PGlite in tests).
-- Safe to run again: every statement is "if not exists".
-- Times are timestamptz (UTC); plain dates (paid-until, invoices) are date.

-- Google terms: only place_id may be kept indefinitely and lat/lng for at most 30 days
-- (see compliance/purge.js). Name, phone etc. here come from RDB, OSM, the business's
-- own site or a visit - never from Google. contact_source records which.
create table if not exists prospects (
  id integer generated by default as identity primary key,
  place_id text unique,
  rdb_number text unique,
  osm_id text unique,
  name text not null,
  sector text not null default 'generic',
  district text,
  sector_admin text,
  lat double precision,
  lng double precision,
  coords_fetched_at timestamptz,
  coords_source text,
  website_url text,
  website_status text,
  score integer,
  score_breakdown text,
  contact_phone text,
  contact_email text,
  contact_source text,
  do_not_contact integer not null default 0,
  stage text not null default 'discovered'
    check (stage in ('discovered', 'audited', 'generated', 'contacted', 'interested', 'won', 'lost', 'dormant')),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists prospects_stage on prospects (stage, score desc);
create index if not exists prospects_score on prospects (score desc nulls last);
create index if not exists prospects_district on prospects (district);

create table if not exists audits (
  id integer generated by default as identity primary key,
  prospect_id integer not null references prospects (id) on delete cascade,
  checked_at timestamptz not null default now(),
  http_status integer,
  final_url text,
  has_https integer,
  is_mobile_friendly integer,
  load_ms integer,
  last_copyright_year integer,
  cms_detected text,
  has_ssl_error integer,
  is_parked integer,
  signals text not null default '{}',
  score integer not null
);
create index if not exists audits_prospect on audits (prospect_id, checked_at desc);

create table if not exists prospect_ai_analyses (
  id integer generated by default as identity primary key,
  prospect_id integer not null references prospects (id) on delete cascade,
  model text not null,
  audit_checked_at timestamptz not null,
  findings text not null default '[]',
  report text not null,
  created_at timestamptz not null default now()
);
alter table prospect_ai_analyses add column if not exists findings text not null default '[]';
create index if not exists prospect_ai_analyses_latest on prospect_ai_analyses (prospect_id, created_at desc, id desc);

-- Facts collected for building a prospect's site (OpenStreetMap + their own website).
create table if not exists research (
  prospect_id integer primary key references prospects (id) on delete cascade,
  collected_at timestamptz not null,
  data text not null
);

-- Raw OpenStreetMap tags (ODbL, storable) saved at import.
create table if not exists osm_tags (
  prospect_id integer primary key references prospects (id) on delete cascade,
  tags text not null,
  fetched_at timestamptz not null default now()
);

create table if not exists generated_sites (
  id integer generated by default as identity primary key,
  prospect_id integer not null references prospects (id) on delete cascade,
  slug text not null,
  template_key text not null,
  brief text not null,
  content text not null,
  content_source text not null,
  preview_url text,
  deploy_id text,
  version integer not null,
  generated_at timestamptz not null default now(),
  approved_by_admin text,
  approved_at timestamptz,
  published_at timestamptz
);
create index if not exists sites_prospect on generated_sites (prospect_id, version desc);
create index if not exists sites_slug on generated_sites (slug, version desc);

create table if not exists clients (
  id integer generated by default as identity primary key,
  prospect_id integer not null unique references prospects (id),
  business_name text not null,
  contact_name text,
  phone text,
  plan text not null default 'monthly' check (plan in ('monthly', 'annual')),
  setup_fee integer not null default 0,
  monthly_fee integer not null default 0,
  domain text,
  live_url text,
  started_at date not null default current_date,
  next_invoice_at date not null,
  status text not null default 'active' check (status in ('active', 'overdue', 'suspended', 'cancelled'))
);

create table if not exists payments (
  id integer generated by default as identity primary key,
  client_id integer not null references clients (id) on delete cascade,
  amount integer not null,
  momo_txid text unique,
  paid_at timestamptz not null default now(),
  covers_until date not null,
  note text
);

create table if not exists outreach_log (
  id integer generated by default as identity primary key,
  prospect_id integer not null references prospects (id) on delete cascade,
  channel text not null check (channel in ('visit', 'call', 'whatsapp', 'sms', 'email', 'note')),
  sent_at timestamptz not null default now(),
  message text,
  outcome text,
  opt_out_at timestamptz
);
create index if not exists outreach_prospect on outreach_log (prospect_id, sent_at desc);

-- Queue for audit / research / generate / deploy work; see jobs/queue.js.
create table if not exists jobs (
  id integer generated by default as identity primary key,
  kind text not null,
  payload text not null default '{}',
  status text not null default 'queued' check (status in ('queued', 'running', 'done', 'failed')),
  attempts integer not null default 0,
  error text,
  run_after timestamptz not null default now(),
  started_at timestamptz,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists jobs_next on jobs (status, run_after);

-- ---------- client portal (see src/portal/) ----------
create table if not exists services (
  id integer generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  price integer,
  delivery_days integer,
  active integer not null default 0,
  sort integer not null default 0,
  i18n text not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists portal_users (
  id integer generated by default as identity primary key,
  name text not null,
  company text not null,
  phone text unique,
  email text unique,
  pass_hash text not null,
  token_version integer not null default 0,
  lang text not null default 'en',
  created_at timestamptz not null default now(),
  last_login_at timestamptz,
  erased_at timestamptz
);

create table if not exists orders (
  id integer generated by default as identity primary key,
  user_id integer not null references portal_users (id),
  service_id integer not null references services (id),
  service_name text not null,
  price integer not null,
  deposit integer not null,
  website text,
  details text not null default '',
  status text not null default 'awaiting_deposit'
    check (status in ('awaiting_deposit', 'in_progress', 'awaiting_final', 'completed', 'cancelled')),
  progress integer not null default 0,
  delivery_note text,
  result_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz
);
create index if not exists orders_user on orders (user_id, created_at desc);
create index if not exists orders_status on orders (status, updated_at desc);

create table if not exists order_payments (
  id integer generated by default as identity primary key,
  order_id integer not null references orders (id) on delete cascade,
  kind text not null check (kind in ('deposit', 'final')),
  amount integer not null,
  momo_txid text not null,
  payer_phone text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by text,
  review_note text
);
create index if not exists order_payments_order on order_payments (order_id, submitted_at);
-- A MoMo transaction pays for one thing only; a rejected report can be sent again.
create unique index if not exists order_payments_txid on order_payments (momo_txid) where status <> 'rejected';

create table if not exists order_updates (
  id integer generated by default as identity primary key,
  order_id integer not null references orders (id) on delete cascade,
  author text not null check (author in ('admin', 'client', 'system')),
  author_name text,
  message text not null,
  progress integer,
  code text,
  params text,
  created_at timestamptz not null default now()
);
create index if not exists order_updates_order on order_updates (order_id, id);

create table if not exists admins (
  id integer generated by default as identity primary key,
  username text not null unique,
  pass_hash text not null,
  token_version integer not null default 0,
  created_at timestamptz not null default now()
);

-- Login and sign-up attempt counters, shared by every server instance (see core/auth.js).
create table if not exists rate_limits (
  key text primary key,
  hits integer not null default 0,
  reset_at timestamptz not null
);

-- Photos uploaded for a business's site. Stored in Supabase Storage in production; the bytes
-- live here only when no storage is configured (local development and tests).
create table if not exists photos (
  prospect_id integer not null references prospects (id) on delete cascade,
  name text not null,
  content_type text not null,
  size integer not null,
  data bytea,
  created_at timestamptz not null default now(),
  primary key (prospect_id, name)
);
